# Generated by Django 5.2.17 on 2026-10-02 17:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
            ],
            options={
                'ordering': ['nombre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio unitario (CLP)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventasApp.cliente')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='discosApp.disco')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='venta_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 1)), name='venta_precio_positivo')],
            },
        ),
    ]
