# Generated by Django 5.2.17 on 2026-10-02 17:36

import discosApp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('genero', models.CharField(max_length=100, verbose_name='género')),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('anio_formacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='año de formación')),
                ('integrantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bio', models.TextField(verbose_name='biografía')),
                ('imagen', models.ImageField(blank=True, upload_to='artistas/', validators=[discosApp.validators.validar_imagen])),
            ],
            options={
                'verbose_name_plural': 'artistas',
                'ordering': ['nombre'],
            },
        ),
    ]
