# Generated by Django 5.2.17 on 2026-10-02 17:36

import discosApp.storage
import discosApp.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('genero', models.CharField(max_length=100, verbose_name='género')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='año')),
                ('formato', models.CharField(choices=[('Vinilo', 'Vinilo'), ('CD', 'CD'), ('Cassette', 'Cassette')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio (CLP)')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, upload_to='discos/', validators=[discosApp.validators.validar_imagen])),
                ('documento', models.FileField(blank=True, storage=discosApp.storage.DocumentosPrivadosStorage(), upload_to='documentos/', validators=[discosApp.validators.validar_documento])),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discos', to='artistasApp.artista')),
            ],
            options={
                'ordering': ['titulo', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio__gte', 1)), name='disco_precio_positivo'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='disco_stock_no_negativo')],
            },
        ),
    ]
